
export const data = [
  
  
  {
    id: 0,
    name: 'Michael Jordan',
    team:'Chicago Bulls',
    position: 'Point-Guard',
    imageURL: 'https://m.media-amazon.com/images/I/51Gvcvml+nL._AC_UF894,1000_QL80_.jpg',
    city:'chigago',
    url:'https://apple.com',
  },
  {
    id: 1,
    name: 'Magic Johnson',
    team:'Los Angeles Lakes',
    position: 'Guard',
    imageURL: 'https://m.media-amazon.com/images/I/51Gvcvml+nL._AC_UF894,1000_QL80_.jpg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id: 2,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id: 3,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id: 4,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id: 5,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id: 6,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id: 7,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id:8,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id:9,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
  {
    id:10,
    name: 'Hakeen Olajuwon',
    team:'Los Angeles Lakes',
    position: 'Point Guard',
    imageURL: 'https://www.cobrockets.co.uk/wp-content/uploads/2022/07/city-of-birmingham-rockets-hakeem-abdul-olajuwon-3-1024x853.jpeg',
    city:'chigago',
    url:'https://google.com',
  },
]